#!/bin/zsh -x

emerge -uDN $@ world

if `return $?`
then
else
    revdep-rebuild

    if hash haskell-updater
    then
        haskell-updater
    fi

    if hash perl-cleaner
    then
        perl-cleaner --all
    fi

    emerge @live-rebuild @module-rebuild @preserved-rebuild
    emerge -uDN --with-bdeps y --backtrack=100 world
fi

if hash npm
then
    npm -g update
fi
