#!/bin/zsh -x

if emerge --backtrack=30 --with-bdeps=y -uDN $@ world
then
else
    revdep-rebuild

    hash haskell-updater && haskell-updater
    hash perl-cleaner    && perl-cleaner --all

    emerge --backtrack=30 --with-bdeps=y @live-rebuild @module-rebuild @preserved-rebuild
    emerge --backtrack=30 --with-bdeps=y -uDN $@ world
fi
